export type Team = { slug: string; name: string; color: string };

export const TEAMS: Team[] = [
  { slug: "atl", name: "Atlanta Hawks", color: "#E03A3E" },
  { slug: "bos", name: "Boston Celtics", color: "#2EAD61" },
  { slug: "bkn", name: "Brooklyn Nets", color: "#B5BCC8" },
  { slug: "cha", name: "Charlotte Hornets", color: "#35C2E8" },
  { slug: "chi", name: "Chicago Bulls", color: "#FF5A5F" },
  { slug: "cle", name: "Cleveland Cavaliers", color: "#FDBB30" },
  { slug: "dal", name: "Dallas Mavericks", color: "#4A90E2" },
  { slug: "den", name: "Denver Nuggets", color: "#FF9F43" },
  { slug: "det", name: "Detroit Pistons", color: "#E83E8C" },
  { slug: "gsw", name: "Golden State Warriors", color: "#C7F464" },
  { slug: "hou", name: "Houston Rockets", color: "#F08080" },
  { slug: "ind", name: "Indiana Pacers", color: "#00D1B2" },
  { slug: "lac", name: "LA Clippers", color: "#F472B6" },
  { slug: "lal", name: "Los Angeles Lakers", color: "#B388FF" },
  { slug: "mem", name: "Memphis Grizzlies", color: "#7C9FD6" },
  { slug: "mia", name: "Miami Heat", color: "#E0115F" },
  { slug: "mil", name: "Milwaukee Bucks", color: "#6BCB77" },
  { slug: "min", name: "Minnesota Timberwolves", color: "#A3E635" },
  { slug: "nop", name: "New Orleans Pelicans", color: "#D4A76A" },
  { slug: "nyk", name: "New York Knicks", color: "#F28C28" },
  { slug: "okc", name: "Oklahoma City Thunder", color: "#60A5FA" },
  { slug: "orl", name: "Orlando Magic", color: "#5EEAD4" },
  { slug: "phi", name: "Philadelphia 76ers", color: "#818CF8" },
  { slug: "phx", name: "Phoenix Suns", color: "#FB923C" },
  { slug: "por", name: "Portland Trail Blazers", color: "#EF4444" },
  { slug: "sac", name: "Sacramento Kings", color: "#A78BFA" },
  { slug: "sas", name: "San Antonio Spurs", color: "#CBD5E1" },
  { slug: "tor", name: "Toronto Raptors", color: "#F43F5E" },
  { slug: "uta", name: "Utah Jazz", color: "#FACC15" },
  { slug: "was", name: "Washington Wizards", color: "#38BDF8" },
];
